### PR TITLE
Fix #571: Unable to deserialize a pojo with IonStruct

### LINKED ISSUE #571: Unable to deserialize a pojo with IonStruct
I am not seeing a good option to serialize/deserialize a simple Pojo with a `null` IonStruct. 

The issue is that by default a null IonStruct gets serialized to `null` but due to this change https://github.com/FasterXML/jackson-dataformats-binary/pull/296 that gets converted to a an IonNull, and fails with argument type mismatch.

Failing testing:

```
  public static class Pojo {    
        @JsonCreator
        public Pojo(@JsonProperty("name") String name, @JsonProperty("data") IonStruct data) {   
            this.name = name;
            this.data = data;
        }
        public String name;
        public IonStruct data;
        
        
        @Override
        public int hashCode() {
            return Objects.hash(data, name);
        }
        @Override
        public boolean equals(Object obj) {
            if (this == obj)
                return true;
            if (obj == null)
                return false;
            if (getClass() != obj.getClass())
                return false;
            Pojo other = (Pojo) obj;
            return Objects.equals(data, other.data) && Objects.equals(name, other.name);
        }
    }

    private final IonSystem ionSystem = IonSystemBuilder.standard().build();
    private final IonValueMapper mapper = new IonValueMapper(ionSystem);

    @Test
    public void testRoundTrip() throws JsonProcessingException {
        Pojo p = new Pojo("test", null);
        String value =  mapper.writeValueAsString(p);
        Assert.assertEquals("{name:\"test\",data:null}", value);
        Pojo p2 = mapper.readValue(value, Pojo.class);
        Assert.assertEquals(p, p2);
    }
```

### PR DESCRIPTION
**Pull request by seadbrane**
(fixes #571)

Make IonValueDeserializer a ContextualDeserializer in order to create the correct Ion null type.   

Also, add new IonParser feature READ_NULL_AS_IONVALUE in order to be able to serialize `null` as either an IonNull or java `null`.

### CODE REVIEW

File: ion/src/main/java/com/fasterxml/jackson/dataformat/ion/IonParser.java [hunk 1]
```diff
@@ -563,6 +575,12 @@ private IonValue getIonValue() throws IOException {
         writer.writeValue(_reader);
         IonValue v = l.get(0);
         v.removeFromContainer();
+
+        if (v.isNullValue() && !Feature.READ_NULL_AS_IONVALUE.enabledIn(_formatFeatures)) {
```
Comment (cowtowncoder) [inline ion/src/main/java/com/fasterxml/jackson/dataformat/ion/IonParser.java]: I know existing is the way it is, but call above to:

    _updateToken(JsonToken.VALUE_EMBEDDED_OBJECT);

looks wrong, given this is called (only) from `getEmbeddedObject()`... which should only be called when we do have `JsonToken.VALUE_EMBEDDED_OBJECT` (and if not, fail).

Would probably make sense to add a comment here to explain logic wrt `!IonType.isContainer(v.getType())` -- I am not sure I understand the logic myself.

File: ion/src/main/java/com/fasterxml/jackson/dataformat/ion/ionvalue/IonValueDeserializer.java [hunk 2]
```diff
@@ -16,21 +16,51 @@
...
+import com.amazon.ion.IonValue;
+import com.amazon.ion.Timestamp;
 
 /**
  * Deserializer that knows how to deserialize an IonValue.
  */
-class IonValueDeserializer extends JsonDeserializer<IonValue> {
+class IonValueDeserializer extends JsonDeserializer<IonValue> implements ContextualDeserializer {
+
+    private final JavaType targetType;
```
Comment (cowtowncoder) [inline ion/src/main/java/com/fasterxml/jackson/dataformat/ion/ionvalue/IonValueDeserializer.java]: Member variables with leading underscore -> `_targetType`

File: ion/src/main/java/com/fasterxml/jackson/dataformat/ion/ionvalue/IonValueDeserializer.java [hunk 3]
```diff
@@ -16,21 +16,51 @@
 
 import java.io.IOException;
 
-import com.amazon.ion.*;
-
 import com.fasterxml.jackson.core.JsonParser;
 import com.fasterxml.jackson.core.JsonToken;
-import com.fasterxml.jackson.databind.*;
+import com.fasterxml.jackson.databind.BeanProperty;
```
Comment (cowtowncoder) [inline ion/src/main/java/com/fasterxml/jackson/dataformat/ion/ionvalue/IonValueDeserializer.java]: Usually fold imports of 5+ from same package.

File: ion/src/main/java/com/fasterxml/jackson/dataformat/ion/ionvalue/IonValueDeserializer.java [hunk 4]
```diff
@@ -62,17 +92,34 @@ public IonValue getNullValue(DeserializationContext ctxt) throws JsonMappingExce
...
+                        IonType containerType = getIonContainerType();
+                        if (containerType != null) {
+                            IonSystem ionSystem = ((IonParser) parser).getIonSystem();
+                            return ionSystem.newNull(containerType);
+                        }
                         return iv;
                     }
                 }
             }
-
```
Comment (cowtowncoder) [inline ion/src/main/java/com/fasterxml/jackson/dataformat/ion/ionvalue/IonValueDeserializer.java:69]: What we also need, to make sure `getNullValue()` call is made for every `null` is override of

```
    @Override
    public AccessPattern getNullAccessPattern() {
        // Default implementation assumes that the null value does not vary, which
        // is usually the case for most implementations. But it is not necessarily
        // `null`; so sub-classes may want to refine further.
        return AccessPattern.CONSTANT;
    }
```

to instead return `AccessPattern.DYNAMIC`: otherwise value returned on first call is cached by parent deserializer.

File: ion/src/test/java/com/fasterxml/jackson/dataformat/ion/ionvalue/IonValueDeserializerTest.java [hunk 5]
```diff
@@ -65,7 +73,7 @@ static class IonValueData extends Data<IonValue> {
     }
 
     private static final IonSystem SYSTEM = IonSystemBuilder.standard().build();
-    private static final IonValueMapper ION_VALUE_MAPPER = new IonValueMapper(SYSTEM, SNAKE_CASE);
+    private final IonValueMapper ION_VALUE_MAPPER = new IonValueMapper(SYSTEM, SNAKE_CASE);
```
Comment (cowtowncoder) [inline ion/src/test/java/com/fasterxml/jackson/dataformat/ion/ionvalue/IonValueDeserializerTest.java]: Why change from `static` to per-instance? Did it fail otherwise? (possibly due to null-value caching)

File: ion/src/test/java/com/fasterxml/jackson/dataformat/ion/ionvalue/IonValueDeserializerTest.java [hunk 6]
```diff
@@ -92,23 +100,49 @@ public void shouldBeAbleToDeserializeIncludingNullList() throws Exception {
...
 
     @Test
-    public void shouldBeAbleToDeserializeNullList() throws Exception {
-        IonValue ion = ion("{c:null.list}");
-
-        IonValueData data = ION_VALUE_MAPPER.readValue(ion, IonValueData.class);
+    public void shouldBeAbleToDeserializeNullToIonNull() throws Exception {
+        String ion = "{c:null}";
+        verifyNullDeserialization(ion, SYSTEM.newNull());
+        ION_VALUE_MAPPER.disable(IonParser.Feature.READ_NULL_AS_IONVALUE);
```
Comment (cowtowncoder) [inline ion/src/test/java/com/fasterxml/jackson/dataformat/ion/ionvalue/IonValueDeserializerTest.java]: Should not try to change configuration of ION_VALUE_MAPPER after use, across methods; not guaranteed to take effect. Instead can create `ObjectReader`, call `ObjectReader.with()` and `.without()` to enable/disable features.

(also makes it easier to merge tests to 3.x as 3.x does not have methods to directly configure `ObjectMapper`)

**Review by cowtowncoder — COMMENTED** [review]
Looks pretty good, couple of things to change.

File: ion/src/test/java/com/fasterxml/jackson/dataformat/ion/ionvalue/IonValueDeserializerTest.java (hunk 6 above)
Comment (seadbrane) [reply ion/src/test/java/com/fasterxml/jackson/dataformat/ion/ionvalue/IonValueDeserializerTest.java]: > Should not try to change configuration of ION_VALUE_MAPPER after use,across methods; not guaranteed to take effect.

Why is that - caching?  

Using `ObjectReader` is not a great option here, since it doesn't support Ion natively.    Will create another `IonValueMapper`.

File: ion/src/test/java/com/fasterxml/jackson/dataformat/ion/ionvalue/IonValueDeserializerTest.java (hunk 5 above)
Comment (seadbrane) [reply ion/src/test/java/com/fasterxml/jackson/dataformat/ion/ionvalue/IonValueDeserializerTest.java]: This was changed so that it can be configured in each test, but not needed if I create a new `IonValueMapper` for the `READ_NULL_AS_IONVALUE` cases.

File: ion/src/main/java/com/fasterxml/jackson/dataformat/ion/IonParser.java (hunk 1 above)
Comment (seadbrane) [reply ion/src/main/java/com/fasterxml/jackson/dataformat/ion/IonParser.java]: A couple of tests fail if this `_updateToken(JsonToken.VALUE_EMBEDDED_OBJECT);` is removed.  Perhaps a 3.0 cleanup activity.

File: ion/src/main/java/com/fasterxml/jackson/dataformat/ion/ionvalue/IonValueDeserializer.java (hunk 4 above)
Comment (seadbrane) [reply ion/src/main/java/com/fasterxml/jackson/dataformat/ion/ionvalue/IonValueDeserializer.java:69]: This is already there on line 125.

File: ion/src/test/java/com/fasterxml/jackson/dataformat/ion/ionvalue/IonValueDeserializerTest.java (hunk 6 above)
Comment (cowtowncoder) [reply ion/src/test/java/com/fasterxml/jackson/dataformat/ion/ionvalue/IonValueDeserializerTest.java]: Yes, indirectly caching of (de)serializers. Some of configuration settings affect construction and so effects remain if settings are changed.
Settings changed here are probably ok, although code won't work in 3.0 as mappers are truly immutable (builders only)

File: ion/src/main/java/com/fasterxml/jackson/dataformat/ion/ionvalue/IonValueDeserializer.java (hunk 4 above)
Comment (cowtowncoder) [reply ion/src/main/java/com/fasterxml/jackson/dataformat/ion/ionvalue/IonValueDeserializer.java:69]: Ok thanks somehow missed it.

File: ion/src/main/java/com/fasterxml/jackson/dataformat/ion/IonParser.java (hunk 1 above)
Comment (cowtowncoder) [reply ion/src/main/java/com/fasterxml/jackson/dataformat/ion/IonParser.java]: Ah. Makes sense there is a reason -- should have caught when these were added (or added comments to explain why/how)
