### PR TITLE
[AVRO] Support of Avro logical type `Decimal`.

### LINKED ISSUE #308: Incorrect serialization for `LogicalType.Decimal` (Java `BigDecimal`)
Your following extension `NonBSGenericDatumWriter` of `GenericDatumWriter` ignores proper support for AVRO's `LogicalType.Decimal` (not calling `Conversions.DecimalConversion`) when dealing with `BigDecimal` types. 

A possible fix (inside `NonBSGenericDatumWriter`) might be:

```java
        case BYTES:
            if (datum instanceof byte[]) {
                super.writeWithoutConversion(schema, ByteBuffer.wrap((byte[]) datum), out);
                return;
            }
            // Try and convert Decimal types, if the logical type indicates it
            LogicalType logicalType = schema.getLogicalType(); 
            if (logicalType instanceof Decimal.LogicalType  ) {
                Conversion<BigDecimal> conversion = data.getConversionByClass(BigDecimal.class, logicalType);
                byte[] decimal = convert(schema, logicalType, conversion, datum);
                super.writeWithoutConversion(schema, ByteBuffer.wrap(decimal), out);
                return;
            }
            break;
```

I'm willing to contribute a PR (including tests), but I'd like to apply it as a fix to 2.13.x branch. 

@cowtowncoder  Let me know what you think

### PR DESCRIPTION
**Pull request by MichalFoksa**
Support of Avro logical type `decimal`.  See [Logical Types - Decimal](https://avro.apache.org/docs/1.11.1/specification/#decimal) specification.

`@Decimal` annotation instructs generator to create schema with logical type decimal in bytes Avro type. To create `decimal` in `fixed` type, the field has to be annotated also with `@AvroFixedSize`.
It only works when log

Limitations:
- Exception is not thrown when other than `BigDecimal` filed is annotated with `@Decimal`. The `@Decimal` annotation is ignored.

BigDecimal serialization is delegated to Apache `org.apache.avro.Conversions.DecimalConversion`. 
It validates whether value fits available schema. If not, then it throws `org.apache.avro.AvroTypeException`.      

BigDecimal deserialization is taken from #133 . Deserialization is implemented in `AvroParserImpl` where decoding from bytes of fixed is delegated to child implementations (`ApacheAvroParserImpl`, resp `JacksonAvroParserImpl`). 

Fixes  #308 , #535.

### CODE REVIEW

**Comment by cowtowncoder** [comment]
@MichalFoksa is this ready? If so, would need to convert from Draft to regular PR.

**Comment by MichalFoksa** [comment]
Functionality is ready - it works.
I want to assert serialized value in `BigDecimalTest`.

Will let you know when done.

**Comment by cowtowncoder** [comment]
> Functionality is ready - it works. I want to assert serialized value in `BigDecimalTest`.
> 
> Will let you know when done.

Sounds good, thanks!

**Comment by MichalFoksa** [comment]
@cowtowncoder PR is ready for review.

File: avro/src/main/java/com/fasterxml/jackson/dataformat/avro/annotation/Decimal.java [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+ * will be "fixed" ({@link org.apache.avro.Schema.Type#FIXED}).
+ * <p>
+ * This annotation is only used during Avro schema generation and does not affect data serialization
+ * or deserialization.
+ *
+ * @since 2.19
+ */
+@Target({ElementType.ANNOTATION_TYPE, ElementType.FIELD})
+@Retention(RetentionPolicy.RUNTIME)
+public @interface Decimal {
```
Comment (cowtowncoder) [inline avro/src/main/java/com/fasterxml/jackson/dataformat/avro/annotation/Decimal.java:23]: Perhaps this should be "namespaced" as `@AvroDecimal`? Similar to existing `@AvroNamespace`.

**Review by cowtowncoder — APPROVED** [review]
Looks good, just one question/suggestion wrt naming of annotation.

**Comment by cowtowncoder** [comment]
> Fixes https://github.com/FasterXML/jackson-dataformats-binary/issues/132 , https://github.com/FasterXML/jackson-dataformats-binary/issues/308 , https://github.com/FasterXML/jackson-dataformats-binary/issues/535.

@MichalFoksa I can see #308 and #535 being fixed, but isn't #132 about Date/Time types?

File: avro/src/main/java/com/fasterxml/jackson/dataformat/avro/annotation/Decimal.java (hunk 1 above)
Comment (MichalFoksa) [reply avro/src/main/java/com/fasterxml/jackson/dataformat/avro/annotation/Decimal.java]: `@Decimal` renamed to `@AvroDecimal`.

**Comment by cowtowncoder** [comment]
@MichalFoksa ah yes. I did close #132, since it does seem completed. Added two others in release notes.
